create table tb_address (id bigint generated by default as identity, user_id bigint, city varchar(255), neighborhood varchar(255), number varchar(255), postal_code varchar(255), state varchar(255), street varchar(255), primary key (id));
create table tb_user (id bigint generated by default as identity, last_modified_at timestamp(6), login varchar(255) unique, name varchar(255), password varchar(255), primary key (id));
alter table if exists tb_address add constraint FKhx6ab79y261wkrfa11h092ft foreign key (user_id) references tb_user;
